# Generated by Django 2.1.7 on 2019-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyOverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('startTime', models.CharField(default=None, max_length=50)),
                ('endTime', models.CharField(default=None, max_length=50)),
                ('isApply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendenceInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('startTime', models.CharField(default=None, max_length=50)),
                ('endTime', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('startTime', models.CharField(default=None, max_length=50)),
                ('endTime', models.CharField(default=None, max_length=50)),
                ('isApply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(default=None, max_length=255)),
                ('tellPhone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
