# Generated by Django 2.1.7 on 2019-09-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveinfor',
            name='remark',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
